# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'BirdsEyeView' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'AFNetworking', '~> 3.0'
  pod 'FBSDKCoreKit', '~> 4.9'
  use_frameworks!

  # Pods for BirdsEyeView

  target 'BirdsEyeViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BirdsEyeViewUITests' do
    # Pods for testing
  end

end
